# Generated by Django 2.0.3 on 2018-07-18 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keshane_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('email_address', models.EmailField(max_length=254)),
            ],
        ),
    ]
